# This is a basic workflow to help you get started with Actions

name: armTemplateDeployment

# Controls when the workflow will run
on:
  push:
    branches:
      - main
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  armDeploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Azure Login
        uses: Azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy Resource Group rg-githubactions
        uses: Azure/arm-deploy@v2
        with:
          scope: subscription
          subscriptionId: b7b2edf5-3b33-4d1b-a916-9f552c4148c5
          region: West Europe
          template: ./arm-templates/resourcegroup.json
          parameters:
            location=westeurope
            resourceGroupName=rg-githubactions
          deploymentName: rg-githubactions
      
      - name: Deploy Storage Account
        uses: Azure/arm-deploy@v2
        id: storageAccountDeploy
        with:
          scope: resourcegroup
          resourceGroupName: rg-githubactions
          subscriptionId: b7b2edf5-3b33-4d1b-a916-9f552c4148c5
          template: ./arm-templates/storageaccount.json
          # Hybrid method: uses both the parameter file and hardcorde (override) parameters
          parameters: 
            ./arm-templates/storageaccount.parameters.json
            storageAccountName=githubstoragetmp02
            location=germanywestcentral
          deploymentMode: incremental
      
      - run: echo ${{ steps.storageAccountDeploy.outputs.BlobUri}}

      - name: Deploy Virtual Machine
        uses: Azure/arm-deploy@v2
        with:
          scope: resourcegroup
          resourceGroupName: rg-githubactions
          subscriptionId: b7b2edf5-3b33-4d1b-a916-9f552c4148c5
          template: ./arm-templates/virtualmachine.json
          # Hybrid method: uses both the parameter file and hardcorde (override) parameters
          parameters: 
            adminPassword=T3stw@chtW
          deploymentMode: incremental
